### ISSUE TITLE
Generalize naming of the parameters

### ISSUE THREAD

**Issue by Perevalov** [WDAqua/Qanary#141]
When running the pipeline e.g., via Docker Compose, one needs to specify the parameters:

```yml
  qanary_pipeline:
    image: qanary/qanary-pipeline:3.3.4
    ports:
             - 8888:8888
    restart: unless-stopped
    environment:
            - SERVER_PORT=8888
            - STARDOG_URL=http://stardog-host:6868/
            - STARDOG_USERNAME=admin
            - STARDOG_PASSWORD=admin
            - QANARY_PROCESS_ALLOW-ADDITIONAL-TRIPLES=false
            - SERVER_HOST=http://server-host
            - QANARY_QUESTIONS_DIRECTORY=/qanary-questions
```

The parameters: `STARDOG_URL, STARDOG_USERNAME, STARDOG_PASSWORD` include the name `STARDOG`, but as I understand, the pipeline can work with any other triplestore.

Suggestion: replace `STARDOG_` with `TRIPLESTORE_`
